<!DOCTYPE html>
<html>
<head>
    <base target="_blank" />
    <style type="text/css">::-webkit-scrollbar{ display: none; }</style>
    <style id="cloudAttachStyle" type="text/css">#divNeteaseBigAttach, #divNeteaseBigAttach_bak{display:none;}</style>
    <style id="blockquoteStyle" type="text/css">blockquote{display:none;}</style>
    <style type="text/css">
        body{font-size:14px;font-family:arial,verdana,sans-serif;line-height:1.666;padding:0;margin:0;overflow:auto;white-space:normal;word-wrap:break-word;min-height:100px}
        td, input, button, select, body{font-family:Helvetica, 'Microsoft Yahei', verdana}
        pre {white-space:pre-wrap;white-space:-moz-pre-wrap;white-space:-pre-wrap;white-space:-o-pre-wrap;word-wrap:break-word;width:95%}
        th,td{font-family:arial,verdana,sans-serif;line-height:1.666}
        img{ border:0}
        header,footer,section,aside,article,nav,hgroup,figure,figcaption{display:block}
        blockquote{margin-right:0px}
    </style>
</head>
<body tabindex="0" role="listitem">
<table width="700" border="0" align="center" cellspacing="0" style="width:700px;">
    <tbody>
    <tr>
        <td>
            <div style="width:700px;margin:0 auto;border-bottom:1px solid #ccc;margin-bottom:30px;">
                <table border="0" cellpadding="0" cellspacing="0" width="700" height="39" style="font:12px Tahoma, Arial, 宋体;">
                    <tbody><tr><td width="210"></td></tr></tbody>
                </table>
            </div>
            <p>Notice of Membership Benefits</p>
            <p>Dear members.</p>
            <p>Continuing with our previous notification regarding today's market anomaly and trade rollback, we have made the following important decisions after further technical analysis and evaluation, in order to protect the stability and fairness of the trading platform, as well as to ensure that the rights and interests of all our members are not jeopardized:</p>
            <p>Withdrawal of trading pairs: We have decided to withdraw the trading pairs PCT/USDT and TIA/USDT with immediate effect. This is due to the fact that these two pairs have been the most severely affected by the recent abnormal market conditions, and their continued existence may have a further negative impact on the normal operation of the platform and the interests of our members.</p>
            <p>Rollback: At the same time, we will roll back all trades generated by these two pairs during the period of abnormal market conditions, i.e., all relevant trades will be considered invalid and will be reversed accordingly. This measure is intended to correct the unreasonable profit situation arising from the abnormal market, to ensure the fairness of the transaction.</p>
            <p>Protection of members' rights and interests: We are fully aware that this decision may cause you inconvenience and concern. Please be assured that we are committed to taking all necessary measures to ensure that the interests of every member are properly protected. For members affected by the withdrawal of these two trading pairs and the subsequent rollback of trades, we will provide a detailed compensation package and communicate the specific details through individual notifications.</p>
            <p>Security and Monitoring Enhancement: We would like to reiterate once again that in order to prevent the recurrence of such incidents, we have strengthened the security measures of the system and will continue to strictly monitor the trading platform to ensure the stability and security of the trading environment.</p>
            <p>We apologize for the inconvenience this has caused and sincerely appreciate your understanding and support. We promise to spare no effort to provide a safer, more stable and fairer trading environment. If you have any questions about this withdrawal of trading pairs, transaction rollback or compensation plan, or need further assistance, please feel free to contact our customer service team.</p>
            <p>Thank you for your understanding and cooperation.</p>
            <p>[Mago Exchange]</p>

        </td>
    </tr>
    </tbody>
</table>
</body>

</html>